[package]
name = "realpix"
version = "0.1.0"
edition = "2024"
description = "A HEALPix implementation in pure rust"
keywords = ["HEALPix"]
license = "Apache-2.0 OR MIT"

[dependencies]
thiserror = "2"