[package]
name = "realpix"
version = "0.1.1"
edition = "2024"
description = "A HEALPix implementation in pure rust"
keywords = ["HEALPix"]
license = "Apache-2.0 OR MIT"

[dependencies]
thiserror = { version = "2", default-features = false }

[features]
default = ["std"]
std = ["thiserror/std"]